insert into roles values('admin');
insert into roles values('user');
insert into roles values('service');

insert into activities values('create a view');
insert into activities values('get any views');
insert into activities values('get any view');
insert into activities values('get own views');
insert into activities values('get own view');
insert into activities values('get view data');
insert into activities values('get view cached data');
insert into activities values('edit own view');
insert into activities values('edit any view');
insert into activities values('delete own view');
insert into activities values('delete any view');
insert into activities values('create credentials');
insert into activities values('logout');
insert into activities values('login');
insert into activities values('get any activities');
insert into activities values('get any roles');
insert into activities values('create activities');
insert into activities values('create roles');
insert into activities values('delete activities');
insert into activities values('delete roles');
insert into activities values('delete activity from role');
insert into activities values('add activity to role');
insert into activities values('delete credentials');
insert into activities values('get any credentials');
insert into activities values('get any credential');
insert into activities values('edit credentials');
insert into activities values('patch credentials');
insert into activities values('get any credentials roles');
insert into activities values('get own credentials roles');
insert into activities values('add role to user');
insert into activities values('delete role from user');
insert into activities values('run task');
insert into activities values('get task');
insert into activities values('get tasks');
insert into activities values('get event subscriptions');
insert into activities values('feature view');
insert into activities values('search entity');
insert into activities values('get wow static data');
insert into activities values('get wow run details');

insert into roles_activities values('admin', 'create a view');
insert into roles_activities values('admin', 'get any views');
insert into roles_activities values('admin', 'get any view');
insert into roles_activities values('admin', 'get own views');
insert into roles_activities values('admin', 'get own view');
insert into roles_activities values('admin', 'get view data');
insert into roles_activities values('admin', 'get view cached data');
insert into roles_activities values('admin', 'edit own view');
insert into roles_activities values('admin', 'edit any view');
insert into roles_activities values('admin', 'delete own view');
insert into roles_activities values('admin', 'delete any view');
insert into roles_activities values('admin', 'create credentials');
insert into roles_activities values('admin', 'logout');
insert into roles_activities values('admin', 'login');
insert into roles_activities values('admin', 'get any activities');
insert into roles_activities values('admin', 'get any roles');
insert into roles_activities values('admin', 'create activities');
insert into roles_activities values('admin', 'create roles');
insert into roles_activities values('admin', 'delete activities');
insert into roles_activities values('admin', 'delete roles');
insert into roles_activities values('admin', 'delete activity from role');
insert into roles_activities values('admin', 'add activity to role');
insert into roles_activities values('admin', 'delete credentials');
insert into roles_activities values('admin', 'get any credentials');
insert into roles_activities values('admin', 'get any credential');
insert into roles_activities values('admin', 'edit credentials');
insert into roles_activities values('admin', 'patch credentials');
insert into roles_activities values('admin', 'get any credentials roles');
insert into roles_activities values('admin', 'get own credentials roles');
insert into roles_activities values('admin', 'add role to user');
insert into roles_activities values('admin', 'delete role from user');
insert into roles_activities values('admin', 'run task');
insert into roles_activities values('admin', 'get task');
insert into roles_activities values('admin', 'get tasks');
insert into roles_activities values('admin', 'get event subscriptions');
insert into roles_activities values('admin', 'feature view');
insert into roles_activities values('admin', 'search entity');
insert into roles_activities values('admin', 'get wow static data');
insert into roles_activities values('admin', 'get wow run details');

insert into roles_activities values('user', 'create a view');
insert into roles_activities values('user', 'get own views');
insert into roles_activities values('user', 'get own view');
insert into roles_activities values('user', 'edit own view');
insert into roles_activities values('user', 'delete own view');
insert into roles_activities values('user', 'logout');
insert into roles_activities values('user', 'login');
insert into roles_activities values('user', 'get own credentials roles');

insert into roles_activities values('service', 'get view data');
insert into roles_activities values('service', 'get view cached data');
insert into roles_activities values('service', 'search entity');
insert into roles_activities values('service', 'get wow static data');
insert into roles_activities values('service', 'get wow run details');

insert into subscriptions (name) values ('views');
insert into subscriptions (name) values ('sync-lol');

