name: Enforce PR Checklist

on:
  pull_request:
    types: [opened, edited, synchronize]

env:
  changelog_checkbox: "i didn't add a changelog entry because this feature didn't need to update changelog"
  unit_test_checkbox: "i didn't add a single test because this feature didn't require unit testing"
  environment_checkbox: "i have tested this feature in an environment (e.g., production, development, local)"

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate PR checklist
        env:
          BODY: ${{ github.event.pull_request.body }}
        id: checklist
        run: |          
          UNCHECKED_CHANGELOG="\[ \] $changelog_checkbox"
          MARKED_CHANGELOG="\[x\] $changelog_checkbox"
          
          UNCHECKED_TEST="\[ \] $unit_test_checkbox"
          MARKED_TEST="\[x\] $unit_test_checkbox"
          
          UNCHECKED_ENV="\[ \] $environment_checkbox"
          MARKED_ENV="\[x\] $environment_checkbox"

          # Check the Changelog checkbox
          if echo "${BODY,,}" | grep -q "$MARKED_CHANGELOG"; then
            echo "Changelog Checkbox is checked"
          elif echo "${BODY,,}" | grep -q "$UNCHECKED_CHANGELOG"; then
            echo "Changelog Checkbox is not checked"
            if git diff --name-only HEAD^ HEAD | grep -q "CHANGELOG.md"; then
              echo "CHANGELOG.md was modified"
            else
              echo "CHANGELOG.md was not modified and Changelog Checkbox is not checked"
              exit 1
          fi
          else
            echo "Changelog Checkbox not found in pull request description"
            exit 1
          fi
          
          # Check the Unit Test checkbox
          if echo "${BODY,,}" | grep -q "$MARKED_TEST"; then
            echo "Unit Test Checkbox is checked"
          elif echo "${BODY,,}" | grep -q "$UNCHECKED_TEST"; then
            echo "Unit Test Checkbox is not checked"
            if git diff --name-only HEAD^ HEAD | grep -q '^src/test/kotlin/'; then
              echo "At least one test file was modified or added in src/test/kotlin"
            else
              echo "No test files modified or added in src/test/kotlin, and Unit Test Checkbox is not checked"
              exit 1
            fi
          else
            echo "Unit Test Checkbox not found in pull request description"
            exit 1
          fi
          
          # Check the Environment checkbox
          if echo "${BODY,,}" | grep -q "$MARKED_ENV"; then
            echo "Environment Checkbox is checked"
          elif echo "${BODY,,}" | grep -q "$UNCHECKED_ENV"; then
            echo "Environment Checkbox is not checked"
            exit 1
          else
            echo "Environment Checkbox not found in pull request description"
            exit 1
          fi
