name: Enforce PR Checklist

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate PR checklist
        id: checklist
        run: |
          # Load PR description into a variable
          pr_body=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")

          # Define required checkboxes in both checked and unchecked forms
          changelog_checkbox_checked="- [x] This PR doesn't need to update changelog"
          changelog_checkbox_unchecked="- [ ] This PR doesn't need to update changelog"
          unit_test_checkbox_checked="- [x] I have either added unit tests for this feature or confirmed it doesn't need unit tests"
          unit_test_checkbox_unchecked="- [ ] I have either added unit tests for this feature or confirmed it doesn't need unit tests"
          environment_checkbox_checked="- [x] I have tested this feature in an environment (e.g., production, development, local)"
          environment_checkbox_unchecked="- [ ] I have tested this feature in an environment (e.g., production, development, local)"

          # Function to check for checkboxes
          check_checkbox() {
            # Use printf to output and grep for required strings
            if ! printf "%s\n" "$pr_body" | grep -Fxq "$1" && ! printf "%s\n" "$pr_body" | grep -Fxq "$2"; then
              echo "::error::$3"
              exit 1
            fi
          }

          # Check each required checkbox
          check_checkbox "$changelog_checkbox_checked" "$changelog_checkbox_unchecked" \
            "Please check the box to indicate if this PR doesn't need to update changelog."

          check_checkbox "$unit_test_checkbox_checked" "$unit_test_checkbox_unchecked" \
            "Please check the box to confirm if unit tests were added or if they're not needed."

          check_checkbox "$environment_checkbox_checked" "$environment_checkbox_unchecked" \
            "Please check the box to confirm the feature was tested in an environment."

          # Changelog update verification if the checkbox is unchecked
          if printf "%s\n" "$pr_body" | grep -Fxq "$changelog_checkbox_unchecked" && ! git diff --name-only origin/main | grep -q "changelog.md"; then
            echo "::error::Changelog entry required. Please add a change in changelog.md or check the box."
            exit 1
          fi
